---
engines:
  duplication:
    exclude_paths:
      - "app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt"
      - "app/src/main/java/org/koreader/launcher/device/epd/**"
      - "app/src/main/java/org/koreader/launcher/device/lights/**"

languages:
  markdown:
    enabled: false

exclude_paths:
  - "jni/**"
