org.gradle.warning.mode=all
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
org.gradle.parallel=true

# Use AndroidX compat libraries
android.useAndroidX=true

# Fallback values used in Gradle build
projectName=luajit-launcher
versCode=1
versName=1.0
assetsPath=../assets
libsPath=../libs

# JNI libraries
sevenZipLib=z

# Compilation features
android.dependency.useConstraints=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
